# ============================================================
# Server Configuration
# ============================================================
server.port=8080
server.servlet.context-path=/

# ============================================================
# Logging Configuration
# ============================================================
logging.level.org.springframework=INFO
logging.level.root=INFO
logging.file.name=logs/global_dorm.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Enable DEBUG level for specific Spring components if needed
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.context.annotation=DEBUG
logging.level.org.springframework.beans.factory=DEBUG
logging.level.org.hibernate=DEBUG

# ============================================================
# API Configurations
# ============================================================
# Distance API (OSRM Routing)
distance.api.url=https://router.project-osrm.org/route/v1
nominatim.api.url=https://nominatim.openstreetmap.org


# Weather API
weather.api.url=https://api.openweathermap.org/data/2.5/weather
weather.api.key=299e6a0bc2a0d4db0f8212a0e992f3c4

# ============================================================
# MongoDB Configuration
# ============================================================
spring.data.mongodb.uri=mongodb://localhost:27017/GlobalRoomDB

# ============================================================
# Application-Specific Configurations
# ============================================================
application.name=Global Dorm Service
application.version=1.0.0

# ============================================================
# Additional Features (Development Only)
# ============================================================
# Enable H2 Console (useful for quick prototyping)
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none

# ============================================================
# Management Configurations
# ============================================================
management.endpoints.web.exposure.include=mappings,health,info


spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.security.user.name=user
spring.security.user.password=user

logging.level.org.springframework.security=DEBUG


# Caching
spring.cache.type=simple


logging.level.org.springframework.cache=DEBUG



